# Python package

# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
    - master
    - beta/*
    - dev/*

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    branch="$(Build.SourceBranch)"
    echo "working on the $branch branch"
    tags=$(curl https://api.github.com/repos/gcarrarom/kubeconfig-cleaner-cli/tags)
    if [[ $branch == *"dev"* ]]; then
      workingOn=$(echo $tags | jq -r "[.[] | select(.name | contains(\"$(echo $branch | rev | cut -d '/' -f 1 | rev)\"))] | sort_by(.name) | reverse | .[0].name ")
      masterVersion=$(echo $workingOn | cut -d 'v' -f 2 | cut -d '.' -f 1)
      echo "Working on Master Version $masterVersion"
      devVersion=$(echo $workingOn | cut -d 'v' -f 2 | cut -d '.' -f 2)
      echo "Working on Dev version $devVersion, increasing..."
      devVersion=$(($devVersion + 1))
      ApplicationVersion="$masterVersion.$devVersion.0"
    elif [[ $branch == *"beta"* ]]; then
      workingOn=$(echo $tags | jq -r "[.[] | select(.name | contains(\"$(echo $branch | rev | cut -d '/' -f 1 | rev)\"))] | sort_by(.name) | reverse | .[0].name ")
      masterVersion=$(echo $workingOn | cut -d 'v' -f 2 | cut -d '.' -f 1)
      echo "Working on Master Version $masterVersion"
      devVersion=$(echo $workingOn | cut -d 'v' -f 2 | cut -d '.' -f 2)
      echo "Working on Dev version $devVersion"
      betaVersion=$(echo $workingOn | cut -d 'v' -f 2 | cut -d '.' -f 3)
      echo "Working on beta version $devVersion, increasing..."
      betaVersion=$(($betaVersion + 1))
      ApplicationVersion="$masterVersion.$devVersion.$betaVersion"
    elif [[ $branch == "master" ]]; then
      workingOn=$(echo $tags | jq -r "sort_by(.name) | reverse | .[0].name ")
      version=$(echo $workingOn | cut -d 'v' -f 2 | cut -d '.' -f 1)
      echo "Working on Master Version $vesion, increasing..."
      newVersion=$(($version + 1))
      ApplicationVersion="$newVersion.0.0"
    else
      echo "Invalid Branch!"
      exit 10
    fi
    echo "Version to be used: $ApplicationVersion"
    echo "##vso[task.setvariable variable=ApplicationVersion]$ApplicationVersion"
    echo "Changing the version of the setup.py file"
    sed -i -e "s/__VERSION__/$ApplicationVersion/g" "$(Build.SourcesDirectory)/setup.py"
  displayName: 'Get application Version'

- script: |
    python -m pip install --upgrade pip
    pip install pytest-cov
    pip install .
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest --junitxml=$(System.DefaultWorkingDirectory)/testResults.xml --cov=kcleaner --cov-report=html --cov-report=xml
  displayName: 'pytest'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFiles: '$(System.DefaultWorkingDirectory)/testResults.xml'
    testRunTitle: Tests

- task: PublishCodeCoverageResults@1
  displayName: "publishing code coverage"
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/test-cov.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/htmlcov'
    additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/htmlcov/**'
    failIfCoverageEmpty: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '*.py'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/code'
    CleanTargetFolder: true
  displayName: 'Copying Python files to the Staging directory'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'README.MD'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/code'
    CleanTargetFolder: true
  displayName: 'Copying ReadMe.md file to the Staging directory'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/code'
    includeRootFolder: true
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/drop/kcleaner-v$(ApplicationVersion)-$(Build.BuildNumber).tar.gz'
    replaceExistingArchive: true
  displayName: 'Archiving release files to tar.gz file'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publishing Drop Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/code'
    ArtifactName: 'code'
    publishLocation: 'Container'
  displayName: 'Publishing Code Artifacts'
